version: '3'

services:
  # define an MQTT Service
  mosquitto:
    image: vimagick/mosquitto
    container_name: mqtt
    ports:
      - "${MOSQUITTO_PORT}:1883"
      - "${MOSQUITTO_WS_PORT}:8080"
      - "${MOSQUITTO_SSL_PORT}:8883"
    volumes:
      - ./mosquitto/data/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      # - ./mosquitto/data/pwfile:/etc/mosquitto/pwfile
      - mosquitto:/var/lib/mosquitto
    restart: always

  # Define an InfluxDB service
  influxdb:
    build: influxdb
    container_name: influxdb
    #user: root
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      INFLUX_DATABASE: "${INFLUXDB_DB}"
      INLFUX_ADMIN_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUX_ADMIN_PASS: "${INFLUXDB_ADMIN_PASSWORD}"
      INFLUX_API_PORT: "${INFLUXDB_API_PORT}"
      INFLUX_HOST: "${INFLUXDB_HOST}"

  # TELEGRAF        
  telegraf:
    build: telegraf
    container_name: telegraf
    links:
      - influxdb
    depends_on:
      - influxdb
    tty: true
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "${INFLUXDB_API_PORT}"
        DATABASE: "telegraf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
        
  # Grafana     
  grafana:
    build: grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - influxdb
    links:
      - influxdb 
    # user: "104"
    environment: 
      GF_INSTALL_PLUGINS: ${GRAFANA_INSTALL_PLUGINS}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_SECRET_KEY: ${GRAFANA_SECURITY_SECRET_KEY}
      GF_USERS_ALLOW_SIGN_UP: "${GRAFANA_USERS_ALLOW_SIGN_UP}"
      GF_USERS_ALLOW_ORG_CREATE: "${GRAFANA_USERS_ALLOW_ORG_CREATE}"
      GF_AUTH_ANONYMOUS_ENABLED: "${GRAFANA_AUTH_ANONYMOUS_ENABLED}"
      GF_AUTH_ANONYMOUS_ORG_NAME: ${GRAFANA_AUTH_ANONYMOUS_ORG_NAME}
      GF_DASHBOARDS_JSON_ENABLED: "${GRAFANA_DASHBOARDS_JSON_ENABLED}"
      GF_DASHBOARDS_JSON_PATH: ${GRAFANA_DASHBOARDS_JSON_PATH}
      GRAFANA_PLUGINS_ENABLED: "${GRAFANA_PLUGINS_ENABLED}"
    volumes: 
      - grafana:/var/lib/grafana
      - grafana-log:/var/log/grafana


volumes:
  mosquitto:
    driver: ${VOLUMES_DRIVER}
  grafana:
    driver: ${VOLUMES_DRIVER}
  grafana-log:
    driver: ${VOLUMES_DRIVER}
  influxdb:
    driver: ${VOLUMES_DRIVER}
